# Generated by Django 3.1.4 on 2022-07-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0002_document_result_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='result_path',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapi.document')),
            ],
        ),
    ]
